# Custom Language File for Launcher Customizer

[ejs.app]
title = "The Site Launcher"

[ejs.landing]
mediaGitHubURL = "https://the-site.fr/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@TheSiterp"
mediaDiscordURL = "https://discord.the-site.fr/"

[ejs.settings]
sourceGithubLink = "https://discord.the-site.fr/"
supportLink = "https://discord.the-site.fr/"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR THE SITE"
welcomeDescription = "The Site est un serveur minecraft SCP RP francophone. En version 1.20.1."
welcomeDescCTA = "Encore un clic pour rejoindre The Site !"
